### ISSUE TITLE
Datalab chart map is not displayed correctly

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#733]
Please find an example from the default installed notebook: ```notebooks/datalab/tutorials/Data/Interactive Charts with Google Charting APIs.ipynb```

The map is single color and the button's icons are not readable:
<img width="1023" alt="datalab map" src="https://cloud.githubusercontent.com/assets/8209940/12005769/592cb8be-ab6b-11e5-987b-c71ad8b3f4a0.png">
The screenshot is on my Chrome browser, on the Safari the single color is replaced by the map but the button icons are still unreadable.

**Comment by gramster** [comment]
The buttons being unreadable is something we are aware of. The single color map means the map didn't load - the push pins can still be drawn independently. These are both Google Charts issues, not specific to Datalab.

**Comment by gramster** [comment]
fixed in 16fb344839582fa15fb2ea891b5b3026e87c01f4

**Comment by VelizarVESSELINOV** [comment]
On my DataLab project is still not working map, what it is needed to deploy your fix on existing DataLab project?

**Comment by VelizarVESSELINOV** [comment]
Works now :)

**Comment by Cecitux** [comment]
@VelizarVESSELINOV  
@gramster 
Could you explain me how to result this issue, I have the following error for see a map.

![image](https://cloud.githubusercontent.com/assets/16903090/16935127/5672b228-4d22-11e6-948c-a019c737f011.png)


Thanks

**Comment by scottma** [comment]
I have the same error here, wonder if anyone has found a solution to this.

**Comment by VelizarVESSELINOV** [comment]
At the end, I stopped using `%%chart map` because of stability and limitation issues, JavaScript Google map call is more reliable, scalable, portable.

**Comment by qimingj** [comment]
Can anyone share a bigquery table with me(qimingj@google.com) and the query to reproduce the issue? I cannot reproduce the error using our sample notebooks.

**Comment by magyarb** [comment]
I can not use the %%chart map, because i get the API error: MissingKeyMapError. Where can i specify my API key?

**Comment by chmeyers** [comment]
MissingKeyMapError is this issue: https://github.com/googledatalab/notebooks/issues/74

**Comment by yebrahim** [comment]
Updated that issue with one possible work around to embed your key in the notebook.
